### ISSUE TITLE
Add fields to data model to support QC efforts

### ISSUE THREAD

**Issue by bheavner** [UW-GAC/gregor_data_models#1]
For example, adding field for consent to subject data table could enable QC that the data uploaded is all  in the same consent group, and agrees with the DULs applied to the AnVIL workspace

**Comment by bheavner** [comment]
note: list of NIH consent codes is available on the template IC form (pg 3) - https://osp.od.nih.gov/wp-content/uploads/GDS_Clinical_Specimen_Certification.pdf

**Comment by smgogarten** [comment]
consent_code is in the participant table. @bheavner can we close this?

**Comment by bheavner** [comment]
yep!
