### ISSUE TITLE
1:1, 1:many, many:1?

### ISSUE THREAD

**Issue by bheavner** [UW-GAC/gregor_data_models#2]
for now, relationships are all 1:1 (a dash in the ref field). Should some be 1:many (<) or many:1 (>) ?

**Comment by bheavner** [comment]
perhaps some many relationships could be useful for anticipated QC problems (e.g. something goes wrong with an experiment ID - useful to just make a new ID that links to experiment detail tables?

**Comment by smgogarten** [comment]
fixed this in v0
