### ISSUE TITLE
dbml syntax error when copying to dbdiagram

### ISSUE THREAD

**Issue by bheavner** [UW-GAC/gregor_data_models#3]
When I copy the current .dbml to dbdiagram.io, I get a syntax error for an enum field:
`enum subject_race {
  American Indian or Alaska Native
  Asian
  Black or African American
  Native Hawaiian or Other Pacific Islander
  Middle Eastern or North African(*??)
  White
  Unknown
}`
gives
`Expected " ", "[", comment, or newline but "I" found. `

**Comment by bheavner** [comment]
It looks like string enumerations need to be enclosed in double quotes. This seems to work:

> enum subject_race {
  "American Indian or Alaska Native"
  "Asian"
  "Black or African American"
  "Native Hawaiian or Other Pacific Islander"
  "Middle Eastern or North African(*??)"
  "White"
  "Unknown"
}

**Comment by smgogarten** [comment]
In the JSON version of the data model, exporting to DBML no longer writes the 'enum' sets
